### ISSUE TITLE
smoothly handle tv weight = 0

### ISSUE THREAD

**Issue by tjlane** [alisiafadini/meteor#26]
@alisiafadini we had discussed that some scripts might make use of a TV weight of zero as a nice way to generalize to not including TV denoising -- do we need to modify the existing code to make this work?

**Comment by alisiafadini** [comment]
@tjlane you could just run TV denoising function with a very low weight (`1e-12`)? Cannot go exactly to TV weight of because in the [scikit-image implementation](https://github.com/scikit-image/scikit-image/blob/v0.24.0/skimage/restoration/_denoise.py#L489-L605) the weight is in the denominator.

**Comment by tjlane** [comment]
better if we just intercept `weight <= 0` and if so return the original map

**Comment by alisiafadini** [comment]
agreed – sounds good to me!
