### ISSUE TITLE
Bug in `compute_scale_factors`

### ISSUE THREAD

**Issue by alisiafadini** [alisiafadini/meteor#31]
At the following lines:

```
    common_reference_values = np.array(reference_values.loc[common_miller_indices])
    common_values_to_scale = np.array(values_to_scale.loc[common_miller_indices])
```

are not passed as numpy arrays the optimization returns incorrect scaling parameters. I am yet to understand exactly why this happens

**Comment by tjlane** [comment]
resolved by #32
